App_Story6_PPW/urls.py
from django.contrib import admin
from django.urls import path
from App_Story6_PPW import views
from App_Story6_PPW.views import StatusModel,  StatusForm

app_name = 'App_Story6_PPW'

urlpatterns = [
    path('my-status/', views.Index6), #isi form nya 
]

Project_Story6_PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Story6_PPW.urls', namespace='App_Story6_PPW')),
]

App_Story6_PPW/models.py
from django.db import models
from django.core.validators import MaxLengthValidator

# Create your models here.
class StatusModel(models.Model):

    Status = models.CharField(max_length = 300, validators = [MaxLengthValidator(limit_value = 300)])
    Date = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return self.Status

App_Story6_PPW/forms.py
from django import forms
from .models import StatusModel

class StatusForm(forms.Form):
    Status = forms.CharField(max_length = 300, label="", widget=forms.TextInput(attrs={'placeholder': "What's your status?"}))

App_Story6_PPW/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from App_Story6_PPW.forms import StatusForm
from App_Story6_PPW.models import StatusModel

def Index6(request):
    semua_status = StatusModel.objects.all()
    sent_data = {"all_status" : semua_status}

    if request.method == "GET":      #Tampilin form-nya
        form = StatusForm()
        sent_data["status_form"] = form #nambahin element ke dict
        return render (request, 'index6.html', sent_data)
    else: 
        isi_form = StatusForm(data=request.POST)     #dict yg isinya data yg telah di submit 
        if isi_form.is_valid():
            new_status = request.POST["Status"]

            new_status_2 = StatusModel(
                Status = new_status,
            )
            new_status_2.save()
            return redirect("/my-status/") #ke halaman hasil form
        else:
            return HttpResponse("NOT SAVED")
            

App_Story6_PPW/templates/IsiStatus.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>
<body>
    <p> status : {{isinya.status}}</p>
</body>
</html>

App_Story6_PPW/templates/index6.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<head>
<title>My Status</title>
</head>
    <style>
        body{
            background-color: rgb(233, 233, 233);
            font-family: Arial, Helvetica, sans-serif;
        }
        .hello{
            text-align: center;
            margin-top: 2vw;
        }
        #id_Status{
            width: 35%;
            padding: 0.5vw;
            margin: 1vw;
            margin-left: 26vw;
            border-radius: 0.5vw;
            border: 0.5px solid #969696;
        }
        .tombol{
            text-align: right;
            margin-right: 18vw;
        }
        .save{
            text-align: center;
            font-size: 20px;
            border-radius: 1vw;
            padding: 0.7vw;
            color: rgb(64, 196, 240);
            background-color: rgb(233,233,233);
            border: 2px solid rgb(64, 196, 240);
        }
        .line{
            width: 78vw;
            height: 3px;
            top: 9vw;
            margin-bottom: 1%;
            margin-top: 1%;
            background: rgb(161, 161, 161);
        }
        .tulisan_status{
            font-family: Arial, Helvetica, sans-serif;
            font-size: 20px;
        }
    </style>
    <body>
        <div class="container">
            <div class="col-12 form">
                <h1 class="hello"> Hey! How are you?</h1>
                <form action="/my-status/" method="post">
                    {% csrf_token %}
                    {{ status_form.as_p }}
                <div class="tombol">
                    <input type="Submit" class="save btn btn-default" value="Submit">
                </div>
                </form>
                {% for take_status in all_status %}
                    <div class="line"></div>
                    <p class="tulisan_status"> Status : {{take_status.Status}} </p>
                    {% timezone "Asia/Jakarta" %}
                        <p> Date : {{take_status.Date}}</p>
                    {% endtimezone %}
                {% endfor %}
            </div>
        </div>
    </body>
</html>